#!/usr/bin/env python3
"""Compiles tools/score.py + the voice bank into src/gen_score.h, src/gen_voice.h and src/gen_voice_64k.h."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import voicebank as vb
import score as S

SRC = os.path.join(HERE, '..', 'src')
VB_PARAMS = dict(thr=2.0, M=16, qscale=3.0, rdb=1.5, uniform=True, lsfit=True, eh=2)
if os.environ.get('VBP'): VB_PARAMS.update(eval('dict(%s)' % os.environ['VBP']))   # experiments
VB_64K = dict(ew=1.3, rdb=1.75)

QUALS = ['m', 'M', '7', 's', '2', 'm9', 'M7', 'm6']
FXK = ['blip', 'cut', 'hum', 'sweep', 'open', 'riser', 'impact', 'echo', 'turn', 'door', 'eyeB', 'eyeR',
       'touch', 'wave', 'shatter', 'hush', 'stop', 'silence', 'blink', 'theme', 'shimmer', 'title']
VOICE = {'A': 0, 'B': 1, 'AB': 2, 'C': 3}
SPK_A = int(os.environ.get("SPKA", "8"))   # the android's source speaker (Kokoro v0.19: 0 af, 1 af_bella, 2 af_nicole,
SPK_B = int(os.environ.get("SPKB", "7"))   # 3 af_sarah, 4 af_sky, 7 bf_emma, 8 bf_isabella); the cyborg's


def chord_code(c):
    r = c[0]; i = 1
    if len(c) > 1 and c[1] in '#b': r += c[1]; i = 2
    root = S.m(r + '4') % 12
    q = c[i:] or 'M'
    return root | (QUALS.index(q) << 4)


def arr_word(d):
    return (d['drums'] | d['bass'] << 3 | d['arp'] << 5 | d['pad'] << 7 | d['lead'] << 9 | d['gran'] << 10 |
            d['drone'] << 12 | d['dark'] << 13 | d['breath'] << 14)


def carr(name, typ, vals):
    return 'static const %s %s[%d]={%s};' % (typ, name, len(vals), ','.join(str(v) for v in vals))


def main():
    lines = vb.read_lyrics()
    vo = [VOICE[v[0]] for v in S.VOX]
    an = vb.analyse_lines(lines, SPK_A)
    # two speakers: the android's words (her lines, the duo, the merged voice) and the cyborg's
    ia = [i for i, v in enumerate(vo) if v != 1]; ib = [i for i, v in enumerate(vo) if v in (1, 2)]
    tb = 'b' if SPK_B != SPK_A else 'a'
    anb = vb.analyse_lines([lines[i] for i in ib], SPK_B)
    L, A, T = [lines[i] for i in ia + ib], [an[i] for i in ia] + anb, ['a'] * len(ia) + [tb] * len(ib)
    bk = vb.build_bank(L, A, tags=T, **VB_PARAMS)
    St = vb.pack(bk)
    idx = vb.emit_header(bk, St, os.path.join(SRC, 'gen_voice.h'))
    # the 64k edition: fewer keyframes where the voice is quiet, coarser loudness steps (same words, same order)
    bk64 = vb.build_bank(L, A, tags=T, **dict(VB_PARAMS, **VB_64K))
    vb.emit_header(bk64, vb.pack(bk64), os.path.join(SRC, 'gen_voice_64k.h'))
    o = ['/* generated by tools/build_data.py from tools/score.py - do not edit */',
         '#define NBARS %d' % S.NBARS, '#define NVL %d' % len(S.VOX), '#define NFX %d' % len(S.FX)]
    o.append(carr('sc_chord', 'unsigned char', [chord_code(S.CH[b]) for b in range(S.NBARS)]))
    o.append(carr('sc_arr', 'unsigned short', [arr_word(S.ARR[b]) for b in range(S.NBARS)]))
    vv, vbar, vnw, vwords, vnn, vnotes = [], [], [], [], [], []
    for l, v in zip(lines, S.VOX):
        vv.append(VOICE[v[0]]); vbar.append(v[1]); vnw.append(len(l['words']))
        for t in ([tb] if v[0] == 'B' else ['a', tb] if v[0] == 'AB' else ['a']):   # a duo line lists both speakers' words
            for w, p in l['words']: vwords.append(idx[t + w.lower() + '=' + ' '.join(p)])
        vnn.append(len(v[2]))
        for notes in (v[2], v[3]):
            if notes is None: continue
            for p, s, d in notes: vnotes += [p, s, d]
    o.append(carr('vl_voice', 'unsigned char', vv))
    o.append(carr('vl_bar', 'unsigned char', vbar))
    o.append(carr('vl_nw', 'unsigned char', vnw))
    o.append(carr('vl_words', 'unsigned char', vwords))
    o.append(carr('vl_nn', 'unsigned char', vnn))
    o.append(carr('vl_notes', 'unsigned char', vnotes))
    # the lyrics as displayed (one line per sung line), for the subtitles
    txt = '\n'.join(l['text'] for l in lines) + '\n'
    o.append('static const char vl_text[] TEXTDATA = "%s";' % txt.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n'))
    ld = []
    for bar, spec in S.LEAD:
        for tok in spec.split():
            p, a, b = tok.split(':'); ld += [S.m(p), int(a) + (bar - S.LEAD[0][0]) * 16, int(b)]
    o.append('#define LEAD_BAR %d' % S.LEAD[0][0])
    o.append('#define NLEAD %d' % (len(ld) // 3))
    o.append(carr('lead_notes', 'unsigned char', ld))
    fx = []
    for bar, pos, k, p in S.FX: fx += [bar, pos | (FXK.index(k) << 4) & 0xff, FXK.index(k) >> 4 | p << 1]
    o.append(carr('fx_ev', 'unsigned char', [x for bar, pos, k, p in S.FX for x in (bar, pos, FXK.index(k), p)]))
    for i, k in enumerate(FXK): o.append('#define FX_%s %d' % (k.upper(), i))
    open(os.path.join(SRC, 'gen_score.h'), 'w').write('\n'.join(o) + '\n')
    print('voice bank: %d words, %d keys, blob %d bytes' % (len(bk['order']), sum(len(bk['bank'][k]['keys']) for k in bk['order']),
                                                             sum(len(v) for v in St.values())))


if __name__ == '__main__':
    main()
