#!/usr/bin/env python3
"""Embeds src/shaders/*.glsl into src/gen_shaders.h (optionally minified)."""
import os, sys, re
HERE = os.path.dirname(os.path.abspath(__file__))
SD = os.path.join(HERE, '..', 'src', 'shaders')
NAMES = ['head', 'vfull', 'vpart', 'lib', 'char', 'scene', 'fpart', 'post']
def cstr(s):
    s = s.replace('\\', '\\\\').replace('"', '\\"')
    return '\n'.join('"%s\\n"' % l for l in s.split('\n'))
# the release drops the look-development test mode (a flat grey studio used for character sheets)
TEST_OFF = [('#define LIGHTS (TESTMODE?1.:U[12].x)', '#define LIGHTS U[12].x'), ('#define TESTMODE (U[15].w>.5)', ''),
            ('if(TESTMODE||gCharOnly)', 'if(gCharOnly)'), (' if(TESTMODE)return e;', ''), ('float lt=TESTMODE?1.:LIGHTS;', 'float lt=LIGHTS;'),
            ('vec3 col=TESTMODE?vec3(.1,.105,.11)*(1.-.4*length(q-.5)):vec3(0);', 'vec3 col=vec3(0);'), ('&&!TESTMODE', '')]


def release(s):
    for a, b in TEST_OFF: s = s.replace(a, b)
    assert 'TESTMODE' not in s
    return s


def main(minify=False):
    out = ['/* generated by tools/embed_shaders.py - do not edit */']
    tot = 0
    if minify:
        import minify_glsl
        srcs = minify_glsl.minify_all({n: release(open(os.path.join(SD, n + '.glsl')).read()) for n in NAMES})
    else:
        srcs = {n: open(os.path.join(SD, n + '.glsl')).read() for n in NAMES}
    for n in NAMES:
        s = srcs[n]; tot += len(s)
        out.append('static const char sh_%s[] TEXTDATA =\n%s;' % (n, cstr(s)))
    open(os.path.join(HERE, '..', 'src', 'gen_shaders.h'), 'w').write('\n'.join(out) + '\n')
    print('shaders: %d bytes%s' % (tot, ' (minified)' if minify else ''))
if __name__ == '__main__':
    main('-m' in sys.argv)
