/* generated by tools/embed_shaders.py - do not edit */
static const char sh_head[] =
"#version 460\n"
"layout(location=0)uniform vec4 U[40];\n"
"#define T U[0].x\n"
"\n";
static const char sh_vfull[] =
"out vec2 q;void main(){vec2 p=vec2(gl_VertexID&1,gl_VertexID>>1)*4.-1.;q=p*.5+.5;gl_Position=vec4(p,0,1);}\n"
"\n";
static const char sh_vpart[] =
"out vec4 d;void main(){gl_Position=vec4(0,0,0,1);gl_PointSize=1.;d=vec4(0);}\n"
"\n";
static const char sh_lib[] =
"\n"
"\n";
static const char sh_scene[] =
"in vec2 q;layout(location=0)out vec4 o;layout(location=1)out float h;void main(){o=vec4(q,.5+.5*sin(T),1);h=1e3;}\n"
"\n";
static const char sh_fpart[] =
"in vec4 d;out vec4 o;void main(){o=d;}\n"
"\n";
static const char sh_post[] =
"in vec2 q;out vec4 o;layout(binding=0)uniform sampler2D A;layout(binding=1)uniform sampler2D B;layout(binding=2)uniform sampler2D X;void main(){\n"
"#ifdef DOWN\n"
"o=texture(A,q);\n"
"#endif\n"
"#ifdef UP\n"
"o=texture(A,q)*.5;\n"
"#endif\n"
"#ifdef FINAL\n"
"vec3 c=texture(A,q).rgb+texture(B,q).rgb*.1;o=vec4(c/(1.+c),1);\n"
"#endif\n"
"}\n"
"\n";
